# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "A convenient CLI for managing git worktrees"
  homepage "https://github.com/sushidev-team/worktree-manager"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.3/worktree-manager_1.0.3_darwin_amd64.tar.gz"
      sha256 "3cfb401abc157c1167caf0b5e0f5e9578838e34442727be4758ea23cb864caf1"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.3/worktree-manager_1.0.3_darwin_arm64.tar.gz"
      sha256 "1a43d6c757080d9fca35d842101134408da2b5af8be1483b19cbb443f102c1bb"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.3/worktree-manager_1.0.3_linux_amd64.tar.gz"
      sha256 "cf4fb55750a2f5fdc05b9d2010c39735f42e1a7f399ac4ebcb3275f4bc7d90de"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.3/worktree-manager_1.0.3_linux_arm64.tar.gz"
      sha256 "fdf36872f23021d65e091ec3c3d823f2fd4695423297393fe60fbcff61ddb45b"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
