# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "A convenient CLI for managing git worktrees"
  homepage "https://github.com/sushidev-team/worktree-manager"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.2/worktree-manager_1.0.2_darwin_amd64.tar.gz"
      sha256 "c4de38cdc666f203dc24575792089401f47b55659472a02ac870c265eba1a682"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.2/worktree-manager_1.0.2_darwin_arm64.tar.gz"
      sha256 "16b3df67844cf42d7360b6915c61c2cf096bae16268176facba14b426f1ddce2"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.2/worktree-manager_1.0.2_linux_amd64.tar.gz"
      sha256 "6948a422d960bd193d1c5abba5756fe0d883aa316e0f105dd622b56c01009ee5"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sushidev-team/worktree-manager/releases/download/v1.0.2/worktree-manager_1.0.2_linux_arm64.tar.gz"
      sha256 "19f3b4cdcfcaa30c454cd16f85c57643692d527dd878b348a95b7362f820dbc3"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
